/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccessTokenIdResponse
 */
public class AccessTokenIdResponseTest {
    private final AccessTokenIdResponse model = new AccessTokenIdResponse();

    /**
     * Model tests for AccessTokenIdResponse
     */
    @Test
    public void testAccessTokenIdResponse() {
        // TODO: test AccessTokenIdResponse
    }

    /**
     * Test the property 'issueAddress'
     */
    @Test
    public void issueAddressTest() {
        // TODO: test issueAddress
    }

    /**
     * Test the property 'issuedDate'
     */
    @Test
    public void issuedDateTest() {
        // TODO: test issuedDate
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

}
