/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AssociatedNormParty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AssociatedNormPartyResponse
 */
public class AssociatedNormPartyResponseTest {
    private final AssociatedNormPartyResponse model = new AssociatedNormPartyResponse();

    /**
     * Model tests for AssociatedNormPartyResponse
     */
    @Test
    public void testAssociatedNormPartyResponse() {
        // TODO: test AssociatedNormPartyResponse
    }

    /**
     * Test the property 'associatedNormPartyArray'
     */
    @Test
    public void associatedNormPartyArrayTest() {
        // TODO: test associatedNormPartyArray
    }

    /**
     * Test the property 'nextPageAPI'
     */
    @Test
    public void nextPageAPITest() {
        // TODO: test nextPageAPI
    }

    /**
     * Test the property 'previousPageAPI'
     */
    @Test
    public void previousPageAPITest() {
        // TODO: test previousPageAPI
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

}
