/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BarRecordPreview
 */
public class BarRecordPreviewTest {
    private final BarRecordPreview model = new BarRecordPreview();

    /**
     * Model tests for BarRecordPreview
     */
    @Test
    public void testBarRecordPreview() {
        // TODO: test BarRecordPreview
    }

    /**
     * Test the property 'barNumber'
     */
    @Test
    public void barNumberTest() {
        // TODO: test barNumber
    }

    /**
     * Test the property 'barSourceType'
     */
    @Test
    public void barSourceTypeTest() {
        // TODO: test barSourceType
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'stateCode'
     */
    @Test
    public void stateCodeTest() {
        // TODO: test stateCode
    }

}
