/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BarSourceDataTenYearDisciplineArrayInner
 */
public class BarSourceDataTenYearDisciplineArrayInnerTest {
    private final BarSourceDataTenYearDisciplineArrayInner model = new BarSourceDataTenYearDisciplineArrayInner();

    /**
     * Model tests for BarSourceDataTenYearDisciplineArrayInner
     */
    @Test
    public void testBarSourceDataTenYearDisciplineArrayInner() {
        // TODO: test BarSourceDataTenYearDisciplineArrayInner
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'actionDate'
     */
    @Test
    public void actionDateTest() {
        // TODO: test actionDate
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

}
