/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BarSourceDataAdministrativeActionsArrayInner;
import com.konfigthis.client.model.BarSourceDataAdvancedDegreeArrayInner;
import com.konfigthis.client.model.BarSourceDataBarStatusArrayInner;
import com.konfigthis.client.model.BarSourceDataBoardCertificationsArrayInner;
import com.konfigthis.client.model.BarSourceDataCommitteesArrayInner;
import com.konfigthis.client.model.BarSourceDataCourtHistoryArrayInner;
import com.konfigthis.client.model.BarSourceDataCourtOfAdmissions;
import com.konfigthis.client.model.BarSourceDataDisciplinaryHistoryArrayInner;
import com.konfigthis.client.model.BarSourceDataDisciplineSummariesArrayInner;
import com.konfigthis.client.model.BarSourceDataEmploymentHistoryArrayInner;
import com.konfigthis.client.model.BarSourceDataFeesOptionsArrayInner;
import com.konfigthis.client.model.BarSourceDataInvolvementsArrayInner;
import com.konfigthis.client.model.BarSourceDataLawSchoolArrayInner;
import com.konfigthis.client.model.BarSourceDataName;
import com.konfigthis.client.model.BarSourceDataOpenActionStatusArrayInner;
import com.konfigthis.client.model.BarSourceDataOtherJurisdictionArrayInner;
import com.konfigthis.client.model.BarSourceDataPublicHearingArrayInner;
import com.konfigthis.client.model.BarSourceDataReasonForInactivation;
import com.konfigthis.client.model.BarSourceDataRelatedCasesArrayInner;
import com.konfigthis.client.model.BarSourceDataSourceInfo;
import com.konfigthis.client.model.BarSourceDataStatewideGrievanceCommitteeHistoryArrayInner;
import com.konfigthis.client.model.BarSourceDataStatusHistoryArrayInner;
import com.konfigthis.client.model.BarSourceDataTenYearDisciplineArrayInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BarSourceData
 */
public class BarSourceDataTest {
    private final BarSourceData model = new BarSourceData();

    /**
     * Model tests for BarSourceData
     */
    @Test
    public void testBarSourceData() {
        // TODO: test BarSourceData
    }

    /**
     * Test the property 'administrativeActionsArray'
     */
    @Test
    public void administrativeActionsArrayTest() {
        // TODO: test administrativeActionsArray
    }

    /**
     * Test the property 'admissionType'
     */
    @Test
    public void admissionTypeTest() {
        // TODO: test admissionType
    }

    /**
     * Test the property 'advancedDegreeArray'
     */
    @Test
    public void advancedDegreeArrayTest() {
        // TODO: test advancedDegreeArray
    }

    /**
     * Test the property 'appellateCourtDistrict'
     */
    @Test
    public void appellateCourtDistrictTest() {
        // TODO: test appellateCourtDistrict
    }

    /**
     * Test the property 'appellateDivisionDepartment'
     */
    @Test
    public void appellateDivisionDepartmentTest() {
        // TODO: test appellateDivisionDepartment
    }

    /**
     * Test the property 'attorneyGroup'
     */
    @Test
    public void attorneyGroupTest() {
        // TODO: test attorneyGroup
    }

    /**
     * Test the property 'authorized'
     */
    @Test
    public void authorizedTest() {
        // TODO: test authorized
    }

    /**
     * Test the property 'barLawFirm'
     */
    @Test
    public void barLawFirmTest() {
        // TODO: test barLawFirm
    }

    /**
     * Test the property 'barServiceClass'
     */
    @Test
    public void barServiceClassTest() {
        // TODO: test barServiceClass
    }

    /**
     * Test the property 'barStatusArray'
     */
    @Test
    public void barStatusArrayTest() {
        // TODO: test barStatusArray
    }

    /**
     * Test the property 'bio'
     */
    @Test
    public void bioTest() {
        // TODO: test bio
    }

    /**
     * Test the property 'boardCertificationsArray'
     */
    @Test
    public void boardCertificationsArrayTest() {
        // TODO: test boardCertificationsArray
    }

    /**
     * Test the property 'boardDistrict'
     */
    @Test
    public void boardDistrictTest() {
        // TODO: test boardDistrict
    }

    /**
     * Test the property 'circuit'
     */
    @Test
    public void circuitTest() {
        // TODO: test circuit
    }

    /**
     * Test the property 'clientsRepresentedArray'
     */
    @Test
    public void clientsRepresentedArrayTest() {
        // TODO: test clientsRepresentedArray
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'committeesArray'
     */
    @Test
    public void committeesArrayTest() {
        // TODO: test committeesArray
    }

    /**
     * Test the property 'courtHistoryArray'
     */
    @Test
    public void courtHistoryArrayTest() {
        // TODO: test courtHistoryArray
    }

    /**
     * Test the property 'courtOfAdmissions'
     */
    @Test
    public void courtOfAdmissionsTest() {
        // TODO: test courtOfAdmissions
    }

    /**
     * Test the property 'courtServiceEmail'
     */
    @Test
    public void courtServiceEmailTest() {
        // TODO: test courtServiceEmail
    }

    /**
     * Test the property 'disciplinaryHistoryArray'
     */
    @Test
    public void disciplinaryHistoryArrayTest() {
        // TODO: test disciplinaryHistoryArray
    }

    /**
     * Test the property 'disciplineSummariesArray'
     */
    @Test
    public void disciplineSummariesArrayTest() {
        // TODO: test disciplineSummariesArray
    }

    /**
     * Test the property 'dismissalsArray'
     */
    @Test
    public void dismissalsArrayTest() {
        // TODO: test dismissalsArray
    }

    /**
     * Test the property 'district'
     */
    @Test
    public void districtTest() {
        // TODO: test district
    }

    /**
     * Test the property 'employmentHistoryArray'
     */
    @Test
    public void employmentHistoryArrayTest() {
        // TODO: test employmentHistoryArray
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'feesOptionsArray'
     */
    @Test
    public void feesOptionsArrayTest() {
        // TODO: test feesOptionsArray
    }

    /**
     * Test the property 'firmSize'
     */
    @Test
    public void firmSizeTest() {
        // TODO: test firmSize
    }

    /**
     * Test the property 'firmWebsite'
     */
    @Test
    public void firmWebsiteTest() {
        // TODO: test firmWebsite
    }

    /**
     * Test the property 'firstAdmittedDate'
     */
    @Test
    public void firstAdmittedDateTest() {
        // TODO: test firstAdmittedDate
    }

    /**
     * Test the property 'firstAdmittedYear'
     */
    @Test
    public void firstAdmittedYearTest() {
        // TODO: test firstAdmittedYear
    }

    /**
     * Test the property 'homeCounty'
     */
    @Test
    public void homeCountyTest() {
        // TODO: test homeCounty
    }

    /**
     * Test the property 'inGoodStanding'
     */
    @Test
    public void inGoodStandingTest() {
        // TODO: test inGoodStanding
    }

    /**
     * Test the property 'insurance'
     */
    @Test
    public void insuranceTest() {
        // TODO: test insurance
    }

    /**
     * Test the property 'involvementsArray'
     */
    @Test
    public void involvementsArrayTest() {
        // TODO: test involvementsArray
    }

    /**
     * Test the property 'judicialDistrict'
     */
    @Test
    public void judicialDistrictTest() {
        // TODO: test judicialDistrict
    }

    /**
     * Test the property 'jurisType'
     */
    @Test
    public void jurisTypeTest() {
        // TODO: test jurisType
    }

    /**
     * Test the property 'languagesArray'
     */
    @Test
    public void languagesArrayTest() {
        // TODO: test languagesArray
    }

    /**
     * Test the property 'lastRenewalDate'
     */
    @Test
    public void lastRenewalDateTest() {
        // TODO: test lastRenewalDate
    }

    /**
     * Test the property 'lawSchoolArray'
     */
    @Test
    public void lawSchoolArrayTest() {
        // TODO: test lawSchoolArray
    }

    /**
     * Test the property 'legalSpecialityArray'
     */
    @Test
    public void legalSpecialityArrayTest() {
        // TODO: test legalSpecialityArray
    }

    /**
     * Test the property 'licenseType'
     */
    @Test
    public void licenseTypeTest() {
        // TODO: test licenseType
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nextRegistration'
     */
    @Test
    public void nextRegistrationTest() {
        // TODO: test nextRegistration
    }

    /**
     * Test the property 'nextRenewalDate'
     */
    @Test
    public void nextRenewalDateTest() {
        // TODO: test nextRenewalDate
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'openActionStatusArray'
     */
    @Test
    public void openActionStatusArrayTest() {
        // TODO: test openActionStatusArray
    }

    /**
     * Test the property 'otherJurisdictionArray'
     */
    @Test
    public void otherJurisdictionArrayTest() {
        // TODO: test otherJurisdictionArray
    }

    /**
     * Test the property 'otherNameArray'
     */
    @Test
    public void otherNameArrayTest() {
        // TODO: test otherNameArray
    }

    /**
     * Test the property 'parish'
     */
    @Test
    public void parishTest() {
        // TODO: test parish
    }

    /**
     * Test the property 'pendingProceedingArray'
     */
    @Test
    public void pendingProceedingArrayTest() {
        // TODO: test pendingProceedingArray
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'practiceAreaArray'
     */
    @Test
    public void practiceAreaArrayTest() {
        // TODO: test practiceAreaArray
    }

    /**
     * Test the property 'practiceLocationArray'
     */
    @Test
    public void practiceLocationArrayTest() {
        // TODO: test practiceLocationArray
    }

    /**
     * Test the property 'privateLawPractice'
     */
    @Test
    public void privateLawPracticeTest() {
        // TODO: test privateLawPractice
    }

    /**
     * Test the property 'profileLastCertified'
     */
    @Test
    public void profileLastCertifiedTest() {
        // TODO: test profileLastCertified
    }

    /**
     * Test the property 'publicHearingArray'
     */
    @Test
    public void publicHearingArrayTest() {
        // TODO: test publicHearingArray
    }

    /**
     * Test the property 'reasonForInactivation'
     */
    @Test
    public void reasonForInactivationTest() {
        // TODO: test reasonForInactivation
    }

    /**
     * Test the property 'relatedCasesArray'
     */
    @Test
    public void relatedCasesArrayTest() {
        // TODO: test relatedCasesArray
    }

    /**
     * Test the property 'sectionsArray'
     */
    @Test
    public void sectionsArrayTest() {
        // TODO: test sectionsArray
    }

    /**
     * Test the property 'servicesArray'
     */
    @Test
    public void servicesArrayTest() {
        // TODO: test servicesArray
    }

    /**
     * Test the property 'sourceInfo'
     */
    @Test
    public void sourceInfoTest() {
        // TODO: test sourceInfo
    }

    /**
     * Test the property 'statewideGrievanceCommitteeHistoryArray'
     */
    @Test
    public void statewideGrievanceCommitteeHistoryArrayTest() {
        // TODO: test statewideGrievanceCommitteeHistoryArray
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusDate'
     */
    @Test
    public void statusDateTest() {
        // TODO: test statusDate
    }

    /**
     * Test the property 'statusHint'
     */
    @Test
    public void statusHintTest() {
        // TODO: test statusHint
    }

    /**
     * Test the property 'statusHistoryArray'
     */
    @Test
    public void statusHistoryArrayTest() {
        // TODO: test statusHistoryArray
    }

    /**
     * Test the property 'tenYearDisciplineArray'
     */
    @Test
    public void tenYearDisciplineArrayTest() {
        // TODO: test tenYearDisciplineArray
    }

    /**
     * Test the property 'undergraduateSchool'
     */
    @Test
    public void undergraduateSchoolTest() {
        // TODO: test undergraduateSchool
    }

    /**
     * Test the property 'yearsOfPractice'
     */
    @Test
    public void yearsOfPracticeTest() {
        // TODO: test yearsOfPractice
    }

}
