/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PreviewDocument;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CaseDocument
 */
public class CaseDocumentTest {
    private final CaseDocument model = new CaseDocument();

    /**
     * Model tests for CaseDocument
     */
    @Test
    public void testCaseDocument() {
        // TODO: test CaseDocument
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'addedToLibraryDate'
     */
    @Test
    public void addedToLibraryDateTest() {
        // TODO: test addedToLibraryDate
    }

    /**
     * Test the property 'caseDocumentId'
     */
    @Test
    public void caseDocumentIdTest() {
        // TODO: test caseDocumentId
    }

    /**
     * Test the property 'childDocumentIdArray'
     */
    @Test
    public void childDocumentIdArrayTest() {
        // TODO: test childDocumentIdArray
    }

    /**
     * Test the property 'documentFiledDate'
     */
    @Test
    public void documentFiledDateTest() {
        // TODO: test documentFiledDate
    }

    /**
     * Test the property 'downloadAPI'
     */
    @Test
    public void downloadAPITest() {
        // TODO: test downloadAPI
    }

    /**
     * Test the property 'estimatedOrderDuration'
     */
    @Test
    public void estimatedOrderDurationTest() {
        // TODO: test estimatedOrderDuration
    }

    /**
     * Test the property 'firstFetchDate'
     */
    @Test
    public void firstFetchDateTest() {
        // TODO: test firstFetchDate
    }

    /**
     * Test the property 'inLibrary'
     */
    @Test
    public void inLibraryTest() {
        // TODO: test inLibrary
    }

    /**
     * Test the property 'isPreviewAvailable'
     */
    @Test
    public void isPreviewAvailableTest() {
        // TODO: test isPreviewAvailable
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'parentDocumentId'
     */
    @Test
    public void parentDocumentIdTest() {
        // TODO: test parentDocumentId
    }

    /**
     * Test the property 'previewDocument'
     */
    @Test
    public void previewDocumentTest() {
        // TODO: test previewDocument
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'sortOrder'
     */
    @Test
    public void sortOrderTest() {
        // TODO: test sortOrder
    }

    /**
     * Test the property 'sourceDataStatus'
     */
    @Test
    public void sourceDataStatusTest() {
        // TODO: test sourceDataStatus
    }

}
