/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CaseCountAnalyticsByNormJudge
 */
public class CaseCountAnalyticsByNormJudgeTest {
    private final CaseCountAnalyticsByNormJudge model = new CaseCountAnalyticsByNormJudge();

    /**
     * Model tests for CaseCountAnalyticsByNormJudge
     */
    @Test
    public void testCaseCountAnalyticsByNormJudge() {
        // TODO: test CaseCountAnalyticsByNormJudge
    }

    /**
     * Test the property 'caseCount'
     */
    @Test
    public void caseCountTest() {
        // TODO: test caseCount
    }

    /**
     * Test the property 'caseSearchAPI'
     */
    @Test
    public void caseSearchAPITest() {
        // TODO: test caseSearchAPI
    }

    /**
     * Test the property 'normJudgeId'
     */
    @Test
    public void normJudgeIdTest() {
        // TODO: test normJudgeId
    }

    /**
     * Test the property 'normJudgeName'
     */
    @Test
    public void normJudgeNameTest() {
        // TODO: test normJudgeName
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

}
