/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ServiceStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CourtServiceStatus
 */
public class CourtServiceStatusTest {
    private final CourtServiceStatus model = new CourtServiceStatus();

    /**
     * Model tests for CourtServiceStatus
     */
    @Test
    public void testCourtServiceStatus() {
        // TODO: test CourtServiceStatus
    }

    /**
     * Test the property 'caseClassIdArray'
     */
    @Test
    public void caseClassIdArrayTest() {
        // TODO: test caseClassIdArray
    }

    /**
     * Test the property 'caseDocumentOrderServiceStatus'
     */
    @Test
    public void caseDocumentOrderServiceStatusTest() {
        // TODO: test caseDocumentOrderServiceStatus
    }

    /**
     * Test the property 'caseTrackServiceStatus'
     */
    @Test
    public void caseTrackServiceStatusTest() {
        // TODO: test caseTrackServiceStatus
    }

    /**
     * Test the property 'caseUpdateServiceStatus'
     */
    @Test
    public void caseUpdateServiceStatusTest() {
        // TODO: test caseUpdateServiceStatus
    }

    /**
     * Test the property 'courtIdArray'
     */
    @Test
    public void courtIdArrayTest() {
        // TODO: test courtIdArray
    }

    /**
     * Test the property 'courtLocationIdArray'
     */
    @Test
    public void courtLocationIdArrayTest() {
        // TODO: test courtLocationIdArray
    }

    /**
     * Test the property 'courtServiceStatusId'
     */
    @Test
    public void courtServiceStatusIdTest() {
        // TODO: test courtServiceStatusId
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'serviceStatusAsOn'
     */
    @Test
    public void serviceStatusAsOnTest() {
        // TODO: test serviceStatusAsOn
    }

}
