/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CaseClassCoverage;
import com.konfigthis.client.model.Court;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CourtCoverage
 */
public class CourtCoverageTest {
    private final CourtCoverage model = new CourtCoverage();

    /**
     * Model tests for CourtCoverage
     */
    @Test
    public void testCourtCoverage() {
        // TODO: test CourtCoverage
    }

    /**
     * Test the property 'caseClassCoverageArray'
     */
    @Test
    public void caseClassCoverageArrayTest() {
        // TODO: test caseClassCoverageArray
    }

    /**
     * Test the property 'court'
     */
    @Test
    public void courtTest() {
        // TODO: test court
    }

    /**
     * Test the property 'lastUpdateCountDate'
     */
    @Test
    public void lastUpdateCountDateTest() {
        // TODO: test lastUpdateCountDate
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'totalCaseCount'
     */
    @Test
    public void totalCaseCountTest() {
        // TODO: test totalCaseCount
    }

    /**
     * Test the property 'totalCaseDocumentInLibraryCount'
     */
    @Test
    public void totalCaseDocumentInLibraryCountTest() {
        // TODO: test totalCaseDocumentInLibraryCount
    }

    /**
     * Test the property 'totalCaseDocumentInLibraryInLastThirtyDaysCount'
     */
    @Test
    public void totalCaseDocumentInLibraryInLastThirtyDaysCountTest() {
        // TODO: test totalCaseDocumentInLibraryInLastThirtyDaysCount
    }

    /**
     * Test the property 'totalCasesInLastThirtyDaysCount'
     */
    @Test
    public void totalCasesInLastThirtyDaysCountTest() {
        // TODO: test totalCasesInLastThirtyDaysCount
    }

    /**
     * Test the property 'totalFreeCaseDocumentCount'
     */
    @Test
    public void totalFreeCaseDocumentCountTest() {
        // TODO: test totalFreeCaseDocumentCount
    }

    /**
     * Test the property 'totalFreeCaseDocumentsInLastThirtyDaysCount'
     */
    @Test
    public void totalFreeCaseDocumentsInLastThirtyDaysCountTest() {
        // TODO: test totalFreeCaseDocumentsInLastThirtyDaysCount
    }

    /**
     * Test the property 'totalPaidCaseDocumentCount'
     */
    @Test
    public void totalPaidCaseDocumentCountTest() {
        // TODO: test totalPaidCaseDocumentCount
    }

    /**
     * Test the property 'totalPaidCaseDocumentsInLastThirtyDaysCount'
     */
    @Test
    public void totalPaidCaseDocumentsInLastThirtyDaysCountTest() {
        // TODO: test totalPaidCaseDocumentsInLastThirtyDaysCount
    }

}
