/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Email
 */
public class EmailTest {
    private final Email model = new Email();

    /**
     * Model tests for Email
     */
    @Test
    public void testEmail() {
        // TODO: test Email
    }

    /**
     * Test the property 'emailId'
     */
    @Test
    public void emailIdTest() {
        // TODO: test emailId
    }

    /**
     * Test the property 'firstFetchDate'
     */
    @Test
    public void firstFetchDateTest() {
        // TODO: test firstFetchDate
    }

    /**
     * Test the property 'isVisible'
     */
    @Test
    public void isVisibleTest() {
        // TODO: test isVisible
    }

    /**
     * Test the property 'lastFetchDate'
     */
    @Test
    public void lastFetchDateTest() {
        // TODO: test lastFetchDate
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

}
