/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NormAttorneySearchResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NormAttorneySearchResponse
 */
public class NormAttorneySearchResponseTest {
    private final NormAttorneySearchResponse model = new NormAttorneySearchResponse();

    /**
     * Model tests for NormAttorneySearchResponse
     */
    @Test
    public void testNormAttorneySearchResponse() {
        // TODO: test NormAttorneySearchResponse
    }

    /**
     * Test the property 'nextPageAPI'
     */
    @Test
    public void nextPageAPITest() {
        // TODO: test nextPageAPI
    }

    /**
     * Test the property 'normAttorneySearchId'
     */
    @Test
    public void normAttorneySearchIdTest() {
        // TODO: test normAttorneySearchId
    }

    /**
     * Test the property 'normAttorneySearchResultArray'
     */
    @Test
    public void normAttorneySearchResultArrayTest() {
        // TODO: test normAttorneySearchResultArray
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    public void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'previousPageAPI'
     */
    @Test
    public void previousPageAPITest() {
        // TODO: test previousPageAPI
    }

    /**
     * Test the property 'q'
     */
    @Test
    public void qTest() {
        // TODO: test q
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

}
