/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Contact;
import com.konfigthis.client.model.NormJudgePublicDataAbaRatings;
import com.konfigthis.client.model.NormJudgePublicDataBio;
import com.konfigthis.client.model.NormJudgePublicDataEducationArrayInner;
import com.konfigthis.client.model.NormJudgePublicDataJudicialSource;
import com.konfigthis.client.model.NormJudgePublicDataNameHistoryArrayInner;
import com.konfigthis.client.model.ServiceHistory;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NormJudgePublicData
 */
public class NormJudgePublicDataTest {
    private final NormJudgePublicData model = new NormJudgePublicData();

    /**
     * Model tests for NormJudgePublicData
     */
    @Test
    public void testNormJudgePublicData() {
        // TODO: test NormJudgePublicData
    }

    /**
     * Test the property 'abaRatings'
     */
    @Test
    public void abaRatingsTest() {
        // TODO: test abaRatings
    }

    /**
     * Test the property 'aliasArray'
     */
    @Test
    public void aliasArrayTest() {
        // TODO: test aliasArray
    }

    /**
     * Test the property 'bio'
     */
    @Test
    public void bioTest() {
        // TODO: test bio
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'educationArray'
     */
    @Test
    public void educationArrayTest() {
        // TODO: test educationArray
    }

    /**
     * Test the property 'firstFetchDate'
     */
    @Test
    public void firstFetchDateTest() {
        // TODO: test firstFetchDate
    }

    /**
     * Test the property 'judicialSource'
     */
    @Test
    public void judicialSourceTest() {
        // TODO: test judicialSource
    }

    /**
     * Test the property 'judicialStatus'
     */
    @Test
    public void judicialStatusTest() {
        // TODO: test judicialStatus
    }

    /**
     * Test the property 'lastFetchDate'
     */
    @Test
    public void lastFetchDateTest() {
        // TODO: test lastFetchDate
    }

    /**
     * Test the property 'lastFetchDateWithUpdates'
     */
    @Test
    public void lastFetchDateWithUpdatesTest() {
        // TODO: test lastFetchDateWithUpdates
    }

    /**
     * Test the property 'nameHistoryArray'
     */
    @Test
    public void nameHistoryArrayTest() {
        // TODO: test nameHistoryArray
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'professionalCareerArray'
     */
    @Test
    public void professionalCareerArrayTest() {
        // TODO: test professionalCareerArray
    }

    /**
     * Test the property 'serviceHistoryArray'
     */
    @Test
    public void serviceHistoryArrayTest() {
        // TODO: test serviceHistoryArray
    }

}
