/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PossibleNormPartyScoreConstituents
 */
public class PossibleNormPartyScoreConstituentsTest {
    private final PossibleNormPartyScoreConstituents model = new PossibleNormPartyScoreConstituents();

    /**
     * Model tests for PossibleNormPartyScoreConstituents
     */
    @Test
    public void testPossibleNormPartyScoreConstituents() {
        // TODO: test PossibleNormPartyScoreConstituents
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'nameSimilarityScore'
     */
    @Test
    public void nameSimilarityScoreTest() {
        // TODO: test nameSimilarityScore
    }

    /**
     * Test the property 'otherPotentialNormParties'
     */
    @Test
    public void otherPotentialNormPartiesTest() {
        // TODO: test otherPotentialNormParties
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'secretaryOfStateId'
     */
    @Test
    public void secretaryOfStateIdTest() {
        // TODO: test secretaryOfStateId
    }

}
