/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ServiceStatusDownDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceStatus
 */
public class ServiceStatusTest {
    private final ServiceStatus model = new ServiceStatus();

    /**
     * Model tests for ServiceStatus
     */
    @Test
    public void testServiceStatus() {
        // TODO: test ServiceStatus
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'serviceDetails'
     */
    @Test
    public void serviceDetailsTest() {
        // TODO: test serviceDetails
    }

    /**
     * Test the property 'serviceStatusDownDetails'
     */
    @Test
    public void serviceStatusDownDetailsTest() {
        // TODO: test serviceStatusDownDetails
    }

    /**
     * Test the property 'serviceUp'
     */
    @Test
    public void serviceUpTest() {
        // TODO: test serviceUp
    }

}
