/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.NatureOfSuit;
import com.konfigthis.client.model.SourceCauseOfAction;
import com.konfigthis.client.model.SourceCharge;
import com.konfigthis.client.model.SourcePageData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SourceCaseData
 */
public class SourceCaseDataTest {
    private final SourceCaseData model = new SourceCaseData();

    /**
     * Model tests for SourceCaseData
     */
    @Test
    public void testSourceCaseData() {
        // TODO: test SourceCaseData
    }

    /**
     * Test the property 'natureOfSuitArray'
     */
    @Test
    public void natureOfSuitArrayTest() {
        // TODO: test natureOfSuitArray
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'sourceCaseStatus'
     */
    @Test
    public void sourceCaseStatusTest() {
        // TODO: test sourceCaseStatus
    }

    /**
     * Test the property 'sourceCaseType'
     */
    @Test
    public void sourceCaseTypeTest() {
        // TODO: test sourceCaseType
    }

    /**
     * Test the property 'sourceCauseOfActionArray'
     */
    @Test
    public void sourceCauseOfActionArrayTest() {
        // TODO: test sourceCauseOfActionArray
    }

    /**
     * Test the property 'sourceChargeArray'
     */
    @Test
    public void sourceChargeArrayTest() {
        // TODO: test sourceChargeArray
    }

    /**
     * Test the property 'sourceCourt'
     */
    @Test
    public void sourceCourtTest() {
        // TODO: test sourceCourt
    }

    /**
     * Test the property 'sourcePageData'
     */
    @Test
    public void sourcePageDataTest() {
        // TODO: test sourcePageData
    }

}
