/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Charge;
import com.konfigthis.client.model.ChargeAdditionalData;
import com.konfigthis.client.model.ChargeDegree;
import com.konfigthis.client.model.ChargeSeverity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CaseCharge
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CaseCharge {
  public static final String SERIALIZED_NAME_CHARGE = "charge";
  @SerializedName(SERIALIZED_NAME_CHARGE)
  private Charge charge;

  public static final String SERIALIZED_NAME_CHARGE_ADDITIONAL_DATA_ARRAY = "chargeAdditionalDataArray";
  @SerializedName(SERIALIZED_NAME_CHARGE_ADDITIONAL_DATA_ARRAY)
  private List<ChargeAdditionalData> chargeAdditionalDataArray = new ArrayList<>();

  public static final String SERIALIZED_NAME_CHARGE_DEGREE = "chargeDegree";
  @SerializedName(SERIALIZED_NAME_CHARGE_DEGREE)
  private ChargeDegree chargeDegree;

  public static final String SERIALIZED_NAME_CHARGE_SEVERITY = "chargeSeverity";
  @SerializedName(SERIALIZED_NAME_CHARGE_SEVERITY)
  private ChargeSeverity chargeSeverity;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private String _object = "CaseCharge";

  public CaseCharge() {
  }

  public CaseCharge charge(Charge charge) {
    
    
    
    
    this.charge = charge;
    return this;
  }

   /**
   * Get charge
   * @return charge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Charge getCharge() {
    return charge;
  }


  public void setCharge(Charge charge) {
    
    
    
    this.charge = charge;
  }


  public CaseCharge chargeAdditionalDataArray(List<ChargeAdditionalData> chargeAdditionalDataArray) {
    
    
    
    
    this.chargeAdditionalDataArray = chargeAdditionalDataArray;
    return this;
  }

  public CaseCharge addChargeAdditionalDataArrayItem(ChargeAdditionalData chargeAdditionalDataArrayItem) {
    this.chargeAdditionalDataArray.add(chargeAdditionalDataArrayItem);
    return this;
  }

   /**
   * Get chargeAdditionalDataArray
   * @return chargeAdditionalDataArray
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<ChargeAdditionalData> getChargeAdditionalDataArray() {
    return chargeAdditionalDataArray;
  }


  public void setChargeAdditionalDataArray(List<ChargeAdditionalData> chargeAdditionalDataArray) {
    
    
    
    this.chargeAdditionalDataArray = chargeAdditionalDataArray;
  }


  public CaseCharge chargeDegree(ChargeDegree chargeDegree) {
    
    
    
    
    this.chargeDegree = chargeDegree;
    return this;
  }

   /**
   * Get chargeDegree
   * @return chargeDegree
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public ChargeDegree getChargeDegree() {
    return chargeDegree;
  }


  public void setChargeDegree(ChargeDegree chargeDegree) {
    
    
    
    this.chargeDegree = chargeDegree;
  }


  public CaseCharge chargeSeverity(ChargeSeverity chargeSeverity) {
    
    
    
    
    this.chargeSeverity = chargeSeverity;
    return this;
  }

   /**
   * Get chargeSeverity
   * @return chargeSeverity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public ChargeSeverity getChargeSeverity() {
    return chargeSeverity;
  }


  public void setChargeSeverity(ChargeSeverity chargeSeverity) {
    
    
    
    this.chargeSeverity = chargeSeverity;
  }


  public CaseCharge _object(String _object) {
    
    
    if (_object != null && _object.length() < 10) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 10.");
    }
    
    this._object = _object;
    return this;
  }

   /**
   * Name of the object
   * @return _object
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "CaseCharge", required = true, value = "Name of the object")

  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    
    
    if (_object != null && _object.length() < 10) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 10.");
    }
    this._object = _object;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CaseCharge instance itself
   */
  public CaseCharge putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseCharge caseCharge = (CaseCharge) o;
    return Objects.equals(this.charge, caseCharge.charge) &&
        Objects.equals(this.chargeAdditionalDataArray, caseCharge.chargeAdditionalDataArray) &&
        Objects.equals(this.chargeDegree, caseCharge.chargeDegree) &&
        Objects.equals(this.chargeSeverity, caseCharge.chargeSeverity) &&
        Objects.equals(this._object, caseCharge._object)&&
        Objects.equals(this.additionalProperties, caseCharge.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(charge, chargeAdditionalDataArray, chargeDegree, chargeSeverity, _object, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseCharge {\n");
    sb.append("    charge: ").append(toIndentedString(charge)).append("\n");
    sb.append("    chargeAdditionalDataArray: ").append(toIndentedString(chargeAdditionalDataArray)).append("\n");
    sb.append("    chargeDegree: ").append(toIndentedString(chargeDegree)).append("\n");
    sb.append("    chargeSeverity: ").append(toIndentedString(chargeSeverity)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("charge");
    openapiFields.add("chargeAdditionalDataArray");
    openapiFields.add("chargeDegree");
    openapiFields.add("chargeSeverity");
    openapiFields.add("object");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("charge");
    openapiRequiredFields.add("chargeAdditionalDataArray");
    openapiRequiredFields.add("chargeDegree");
    openapiRequiredFields.add("chargeSeverity");
    openapiRequiredFields.add("object");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CaseCharge
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CaseCharge.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CaseCharge is not found in the empty JSON string", CaseCharge.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CaseCharge.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `charge`
      Charge.validateJsonObject(jsonObj.getAsJsonObject("charge"));
      // ensure the json data is an array
      if (!jsonObj.get("chargeAdditionalDataArray").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `chargeAdditionalDataArray` to be an array in the JSON string but got `%s`", jsonObj.get("chargeAdditionalDataArray").toString()));
      }

      JsonArray jsonArraychargeAdditionalDataArray = jsonObj.getAsJsonArray("chargeAdditionalDataArray");
      // validate the required field `chargeAdditionalDataArray` (array)
      for (int i = 0; i < jsonArraychargeAdditionalDataArray.size(); i++) {
        ChargeAdditionalData.validateJsonObject(jsonArraychargeAdditionalDataArray.get(i).getAsJsonObject());
      };
      // validate the required field `chargeDegree`
      ChargeDegree.validateJsonObject(jsonObj.getAsJsonObject("chargeDegree"));
      // validate the required field `chargeSeverity`
      ChargeSeverity.validateJsonObject(jsonObj.getAsJsonObject("chargeSeverity"));
      if (!jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CaseCharge.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CaseCharge' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CaseCharge> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CaseCharge.class));

       return (TypeAdapter<T>) new TypeAdapter<CaseCharge>() {
           @Override
           public void write(JsonWriter out, CaseCharge value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CaseCharge read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CaseCharge instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CaseCharge given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CaseCharge
  * @throws IOException if the JSON string is invalid with respect to CaseCharge
  */
  public static CaseCharge fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CaseCharge.class);
  }

 /**
  * Convert an instance of CaseCharge to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

