/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PossibleNormAttorneyScoreConstituents;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PossibleNormAttorney
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PossibleNormAttorney {
  public static final String SERIALIZED_NAME_ASSOCIATED_NORM_JUDGES_A_P_I = "associatedNormJudgesAPI";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_NORM_JUDGES_A_P_I)
  private URI associatedNormJudgesAPI;

  public static final String SERIALIZED_NAME_ASSOCIATED_NORM_LAW_FIRMS_A_P_I = "associatedNormLawFirmsAPI";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_NORM_LAW_FIRMS_A_P_I)
  private URI associatedNormLawFirmsAPI;

  public static final String SERIALIZED_NAME_ASSOCIATED_NORM_PARTIES_A_P_I = "associatedNormPartiesAPI";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_NORM_PARTIES_A_P_I)
  private URI associatedNormPartiesAPI;

  public static final String SERIALIZED_NAME_BEST_MATCH = "bestMatch";
  @SerializedName(SERIALIZED_NAME_BEST_MATCH)
  private Boolean bestMatch = false;

  public static final String SERIALIZED_NAME_CASE_COUNT_ANALYTICS_BY_NORM_ATTORNEY_A_P_I = "caseCountAnalyticsByNormAttorneyAPI";
  @SerializedName(SERIALIZED_NAME_CASE_COUNT_ANALYTICS_BY_NORM_ATTORNEY_A_P_I)
  private URI caseCountAnalyticsByNormAttorneyAPI;

  public static final String SERIALIZED_NAME_CASE_COUNT_ANALYTICS_BY_OPPOSING_NORM_ATTORNEY_A_P_I = "caseCountAnalyticsByOpposingNormAttorneyAPI";
  @SerializedName(SERIALIZED_NAME_CASE_COUNT_ANALYTICS_BY_OPPOSING_NORM_ATTORNEY_A_P_I)
  private URI caseCountAnalyticsByOpposingNormAttorneyAPI;

  public static final String SERIALIZED_NAME_CONFIDENCE_SCORE = "confidenceScore";
  @SerializedName(SERIALIZED_NAME_CONFIDENCE_SCORE)
  private Float confidenceScore;

  public static final String SERIALIZED_NAME_NORM_ATTORNEY_A_P_I = "normAttorneyAPI";
  @SerializedName(SERIALIZED_NAME_NORM_ATTORNEY_A_P_I)
  private URI normAttorneyAPI;

  public static final String SERIALIZED_NAME_NORM_ATTORNEY_ID = "normAttorneyId";
  @SerializedName(SERIALIZED_NAME_NORM_ATTORNEY_ID)
  private String normAttorneyId;

  public static final String SERIALIZED_NAME_NORM_ATTORNEY_NAME = "normAttorneyName";
  @SerializedName(SERIALIZED_NAME_NORM_ATTORNEY_NAME)
  private String normAttorneyName;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private String _object = "PossibleNormAttorney";

  public static final String SERIALIZED_NAME_SCORE_CONSTITUENTS = "scoreConstituents";
  @SerializedName(SERIALIZED_NAME_SCORE_CONSTITUENTS)
  private PossibleNormAttorneyScoreConstituents scoreConstituents;

  public PossibleNormAttorney() {
  }

  public PossibleNormAttorney associatedNormJudgesAPI(URI associatedNormJudgesAPI) {
    
    
    
    
    this.associatedNormJudgesAPI = associatedNormJudgesAPI;
    return this;
  }

   /**
   * Get associatedNormJudgesAPI
   * @return associatedNormJudgesAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getAssociatedNormJudgesAPI() {
    return associatedNormJudgesAPI;
  }


  public void setAssociatedNormJudgesAPI(URI associatedNormJudgesAPI) {
    
    
    
    this.associatedNormJudgesAPI = associatedNormJudgesAPI;
  }


  public PossibleNormAttorney associatedNormLawFirmsAPI(URI associatedNormLawFirmsAPI) {
    
    
    
    
    this.associatedNormLawFirmsAPI = associatedNormLawFirmsAPI;
    return this;
  }

   /**
   * Get associatedNormLawFirmsAPI
   * @return associatedNormLawFirmsAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getAssociatedNormLawFirmsAPI() {
    return associatedNormLawFirmsAPI;
  }


  public void setAssociatedNormLawFirmsAPI(URI associatedNormLawFirmsAPI) {
    
    
    
    this.associatedNormLawFirmsAPI = associatedNormLawFirmsAPI;
  }


  public PossibleNormAttorney associatedNormPartiesAPI(URI associatedNormPartiesAPI) {
    
    
    
    
    this.associatedNormPartiesAPI = associatedNormPartiesAPI;
    return this;
  }

   /**
   * Get associatedNormPartiesAPI
   * @return associatedNormPartiesAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getAssociatedNormPartiesAPI() {
    return associatedNormPartiesAPI;
  }


  public void setAssociatedNormPartiesAPI(URI associatedNormPartiesAPI) {
    
    
    
    this.associatedNormPartiesAPI = associatedNormPartiesAPI;
  }


  public PossibleNormAttorney bestMatch(Boolean bestMatch) {
    
    
    
    
    this.bestMatch = bestMatch;
    return this;
  }

   /**
   * Get bestMatch
   * @return bestMatch
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "false", required = true, value = "")

  public Boolean getBestMatch() {
    return bestMatch;
  }


  public void setBestMatch(Boolean bestMatch) {
    
    
    
    this.bestMatch = bestMatch;
  }


  public PossibleNormAttorney caseCountAnalyticsByNormAttorneyAPI(URI caseCountAnalyticsByNormAttorneyAPI) {
    
    
    
    
    this.caseCountAnalyticsByNormAttorneyAPI = caseCountAnalyticsByNormAttorneyAPI;
    return this;
  }

   /**
   * Get caseCountAnalyticsByNormAttorneyAPI
   * @return caseCountAnalyticsByNormAttorneyAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getCaseCountAnalyticsByNormAttorneyAPI() {
    return caseCountAnalyticsByNormAttorneyAPI;
  }


  public void setCaseCountAnalyticsByNormAttorneyAPI(URI caseCountAnalyticsByNormAttorneyAPI) {
    
    
    
    this.caseCountAnalyticsByNormAttorneyAPI = caseCountAnalyticsByNormAttorneyAPI;
  }


  public PossibleNormAttorney caseCountAnalyticsByOpposingNormAttorneyAPI(URI caseCountAnalyticsByOpposingNormAttorneyAPI) {
    
    
    
    
    this.caseCountAnalyticsByOpposingNormAttorneyAPI = caseCountAnalyticsByOpposingNormAttorneyAPI;
    return this;
  }

   /**
   * Get caseCountAnalyticsByOpposingNormAttorneyAPI
   * @return caseCountAnalyticsByOpposingNormAttorneyAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getCaseCountAnalyticsByOpposingNormAttorneyAPI() {
    return caseCountAnalyticsByOpposingNormAttorneyAPI;
  }


  public void setCaseCountAnalyticsByOpposingNormAttorneyAPI(URI caseCountAnalyticsByOpposingNormAttorneyAPI) {
    
    
    
    this.caseCountAnalyticsByOpposingNormAttorneyAPI = caseCountAnalyticsByOpposingNormAttorneyAPI;
  }


  public PossibleNormAttorney confidenceScore(Float confidenceScore) {
    
    
    
    
    this.confidenceScore = confidenceScore;
    return this;
  }

   /**
   * Get confidenceScore
   * @return confidenceScore
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Float getConfidenceScore() {
    return confidenceScore;
  }


  public void setConfidenceScore(Float confidenceScore) {
    
    
    
    this.confidenceScore = confidenceScore;
  }


  public PossibleNormAttorney normAttorneyAPI(URI normAttorneyAPI) {
    
    
    
    
    this.normAttorneyAPI = normAttorneyAPI;
    return this;
  }

   /**
   * Get normAttorneyAPI
   * @return normAttorneyAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getNormAttorneyAPI() {
    return normAttorneyAPI;
  }


  public void setNormAttorneyAPI(URI normAttorneyAPI) {
    
    
    
    this.normAttorneyAPI = normAttorneyAPI;
  }


  public PossibleNormAttorney normAttorneyId(String normAttorneyId) {
    
    
    if (normAttorneyId != null && normAttorneyId.length() < 18) {
      throw new IllegalArgumentException("Invalid value for normAttorneyId. Length must be greater than or equal to 18.");
    }
    
    this.normAttorneyId = normAttorneyId;
    return this;
  }

   /**
   * Get normAttorneyId
   * @return normAttorneyId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNormAttorneyId() {
    return normAttorneyId;
  }


  public void setNormAttorneyId(String normAttorneyId) {
    
    
    if (normAttorneyId != null && normAttorneyId.length() < 18) {
      throw new IllegalArgumentException("Invalid value for normAttorneyId. Length must be greater than or equal to 18.");
    }
    this.normAttorneyId = normAttorneyId;
  }


  public PossibleNormAttorney normAttorneyName(String normAttorneyName) {
    
    
    
    
    this.normAttorneyName = normAttorneyName;
    return this;
  }

   /**
   * Get normAttorneyName
   * @return normAttorneyName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNormAttorneyName() {
    return normAttorneyName;
  }


  public void setNormAttorneyName(String normAttorneyName) {
    
    
    
    this.normAttorneyName = normAttorneyName;
  }


  public PossibleNormAttorney _object(String _object) {
    
    
    if (_object != null && _object.length() < 20) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 20.");
    }
    
    this._object = _object;
    return this;
  }

   /**
   * Name of the object
   * @return _object
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "PossibleNormAttorney", required = true, value = "Name of the object")

  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    
    
    if (_object != null && _object.length() < 20) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 20.");
    }
    this._object = _object;
  }


  public PossibleNormAttorney scoreConstituents(PossibleNormAttorneyScoreConstituents scoreConstituents) {
    
    
    
    
    this.scoreConstituents = scoreConstituents;
    return this;
  }

   /**
   * Get scoreConstituents
   * @return scoreConstituents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public PossibleNormAttorneyScoreConstituents getScoreConstituents() {
    return scoreConstituents;
  }


  public void setScoreConstituents(PossibleNormAttorneyScoreConstituents scoreConstituents) {
    
    
    
    this.scoreConstituents = scoreConstituents;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PossibleNormAttorney instance itself
   */
  public PossibleNormAttorney putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PossibleNormAttorney possibleNormAttorney = (PossibleNormAttorney) o;
    return Objects.equals(this.associatedNormJudgesAPI, possibleNormAttorney.associatedNormJudgesAPI) &&
        Objects.equals(this.associatedNormLawFirmsAPI, possibleNormAttorney.associatedNormLawFirmsAPI) &&
        Objects.equals(this.associatedNormPartiesAPI, possibleNormAttorney.associatedNormPartiesAPI) &&
        Objects.equals(this.bestMatch, possibleNormAttorney.bestMatch) &&
        Objects.equals(this.caseCountAnalyticsByNormAttorneyAPI, possibleNormAttorney.caseCountAnalyticsByNormAttorneyAPI) &&
        Objects.equals(this.caseCountAnalyticsByOpposingNormAttorneyAPI, possibleNormAttorney.caseCountAnalyticsByOpposingNormAttorneyAPI) &&
        Objects.equals(this.confidenceScore, possibleNormAttorney.confidenceScore) &&
        Objects.equals(this.normAttorneyAPI, possibleNormAttorney.normAttorneyAPI) &&
        Objects.equals(this.normAttorneyId, possibleNormAttorney.normAttorneyId) &&
        Objects.equals(this.normAttorneyName, possibleNormAttorney.normAttorneyName) &&
        Objects.equals(this._object, possibleNormAttorney._object) &&
        Objects.equals(this.scoreConstituents, possibleNormAttorney.scoreConstituents)&&
        Objects.equals(this.additionalProperties, possibleNormAttorney.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associatedNormJudgesAPI, associatedNormLawFirmsAPI, associatedNormPartiesAPI, bestMatch, caseCountAnalyticsByNormAttorneyAPI, caseCountAnalyticsByOpposingNormAttorneyAPI, confidenceScore, normAttorneyAPI, normAttorneyId, normAttorneyName, _object, scoreConstituents, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PossibleNormAttorney {\n");
    sb.append("    associatedNormJudgesAPI: ").append(toIndentedString(associatedNormJudgesAPI)).append("\n");
    sb.append("    associatedNormLawFirmsAPI: ").append(toIndentedString(associatedNormLawFirmsAPI)).append("\n");
    sb.append("    associatedNormPartiesAPI: ").append(toIndentedString(associatedNormPartiesAPI)).append("\n");
    sb.append("    bestMatch: ").append(toIndentedString(bestMatch)).append("\n");
    sb.append("    caseCountAnalyticsByNormAttorneyAPI: ").append(toIndentedString(caseCountAnalyticsByNormAttorneyAPI)).append("\n");
    sb.append("    caseCountAnalyticsByOpposingNormAttorneyAPI: ").append(toIndentedString(caseCountAnalyticsByOpposingNormAttorneyAPI)).append("\n");
    sb.append("    confidenceScore: ").append(toIndentedString(confidenceScore)).append("\n");
    sb.append("    normAttorneyAPI: ").append(toIndentedString(normAttorneyAPI)).append("\n");
    sb.append("    normAttorneyId: ").append(toIndentedString(normAttorneyId)).append("\n");
    sb.append("    normAttorneyName: ").append(toIndentedString(normAttorneyName)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    scoreConstituents: ").append(toIndentedString(scoreConstituents)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("associatedNormJudgesAPI");
    openapiFields.add("associatedNormLawFirmsAPI");
    openapiFields.add("associatedNormPartiesAPI");
    openapiFields.add("bestMatch");
    openapiFields.add("caseCountAnalyticsByNormAttorneyAPI");
    openapiFields.add("caseCountAnalyticsByOpposingNormAttorneyAPI");
    openapiFields.add("confidenceScore");
    openapiFields.add("normAttorneyAPI");
    openapiFields.add("normAttorneyId");
    openapiFields.add("normAttorneyName");
    openapiFields.add("object");
    openapiFields.add("scoreConstituents");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("associatedNormJudgesAPI");
    openapiRequiredFields.add("associatedNormLawFirmsAPI");
    openapiRequiredFields.add("associatedNormPartiesAPI");
    openapiRequiredFields.add("bestMatch");
    openapiRequiredFields.add("caseCountAnalyticsByNormAttorneyAPI");
    openapiRequiredFields.add("caseCountAnalyticsByOpposingNormAttorneyAPI");
    openapiRequiredFields.add("confidenceScore");
    openapiRequiredFields.add("normAttorneyAPI");
    openapiRequiredFields.add("normAttorneyId");
    openapiRequiredFields.add("normAttorneyName");
    openapiRequiredFields.add("object");
    openapiRequiredFields.add("scoreConstituents");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PossibleNormAttorney
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PossibleNormAttorney.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PossibleNormAttorney is not found in the empty JSON string", PossibleNormAttorney.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PossibleNormAttorney.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("associatedNormJudgesAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `associatedNormJudgesAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("associatedNormJudgesAPI").toString()));
      }
      if (!jsonObj.get("associatedNormLawFirmsAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `associatedNormLawFirmsAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("associatedNormLawFirmsAPI").toString()));
      }
      if (!jsonObj.get("associatedNormPartiesAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `associatedNormPartiesAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("associatedNormPartiesAPI").toString()));
      }
      if (!jsonObj.get("caseCountAnalyticsByNormAttorneyAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caseCountAnalyticsByNormAttorneyAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseCountAnalyticsByNormAttorneyAPI").toString()));
      }
      if (!jsonObj.get("caseCountAnalyticsByOpposingNormAttorneyAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caseCountAnalyticsByOpposingNormAttorneyAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseCountAnalyticsByOpposingNormAttorneyAPI").toString()));
      }
      if (!jsonObj.get("normAttorneyAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normAttorneyAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normAttorneyAPI").toString()));
      }
      if (!jsonObj.get("normAttorneyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normAttorneyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normAttorneyId").toString()));
      }
      if (!jsonObj.get("normAttorneyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normAttorneyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normAttorneyName").toString()));
      }
      if (!jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
      // validate the required field `scoreConstituents`
      PossibleNormAttorneyScoreConstituents.validateJsonObject(jsonObj.getAsJsonObject("scoreConstituents"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PossibleNormAttorney.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PossibleNormAttorney' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PossibleNormAttorney> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PossibleNormAttorney.class));

       return (TypeAdapter<T>) new TypeAdapter<PossibleNormAttorney>() {
           @Override
           public void write(JsonWriter out, PossibleNormAttorney value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PossibleNormAttorney read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PossibleNormAttorney instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PossibleNormAttorney given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PossibleNormAttorney
  * @throws IOException if the JSON string is invalid with respect to PossibleNormAttorney
  */
  public static PossibleNormAttorney fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PossibleNormAttorney.class);
  }

 /**
  * Convert an instance of PossibleNormAttorney to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

