/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PossibleNormJudgeScoreConstituents;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PossibleNormJudge
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PossibleNormJudge {
  public static final String SERIALIZED_NAME_ASSOCIATED_NORM_ATTORNEYS_A_P_I = "associatedNormAttorneysAPI";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_NORM_ATTORNEYS_A_P_I)
  private URI associatedNormAttorneysAPI;

  public static final String SERIALIZED_NAME_ASSOCIATED_NORM_LAW_FIRMS_A_P_I = "associatedNormLawFirmsAPI";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_NORM_LAW_FIRMS_A_P_I)
  private URI associatedNormLawFirmsAPI;

  public static final String SERIALIZED_NAME_ASSOCIATED_NORM_PARTIES_A_P_I = "associatedNormPartiesAPI";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_NORM_PARTIES_A_P_I)
  private URI associatedNormPartiesAPI;

  public static final String SERIALIZED_NAME_BEST_MATCH = "bestMatch";
  @SerializedName(SERIALIZED_NAME_BEST_MATCH)
  private Boolean bestMatch = false;

  public static final String SERIALIZED_NAME_CASE_COUNT_ANALYTICS_BY_NORM_JUDGE_A_P_I = "caseCountAnalyticsByNormJudgeAPI";
  @SerializedName(SERIALIZED_NAME_CASE_COUNT_ANALYTICS_BY_NORM_JUDGE_A_P_I)
  private URI caseCountAnalyticsByNormJudgeAPI;

  public static final String SERIALIZED_NAME_CONFIDENCE_SCORE = "confidenceScore";
  @SerializedName(SERIALIZED_NAME_CONFIDENCE_SCORE)
  private Float confidenceScore;

  public static final String SERIALIZED_NAME_NORM_JUDGE_A_P_I = "normJudgeAPI";
  @SerializedName(SERIALIZED_NAME_NORM_JUDGE_A_P_I)
  private URI normJudgeAPI;

  public static final String SERIALIZED_NAME_NORM_JUDGE_ID = "normJudgeId";
  @SerializedName(SERIALIZED_NAME_NORM_JUDGE_ID)
  private String normJudgeId;

  public static final String SERIALIZED_NAME_NORM_JUDGE_NAME = "normJudgeName";
  @SerializedName(SERIALIZED_NAME_NORM_JUDGE_NAME)
  private String normJudgeName;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private String _object = "PossibleNormJudge";

  public static final String SERIALIZED_NAME_SCORE_CONSTITUENTS = "scoreConstituents";
  @SerializedName(SERIALIZED_NAME_SCORE_CONSTITUENTS)
  private PossibleNormJudgeScoreConstituents scoreConstituents;

  public PossibleNormJudge() {
  }

  public PossibleNormJudge associatedNormAttorneysAPI(URI associatedNormAttorneysAPI) {
    
    
    
    
    this.associatedNormAttorneysAPI = associatedNormAttorneysAPI;
    return this;
  }

   /**
   * Get associatedNormAttorneysAPI
   * @return associatedNormAttorneysAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "https://enterpriseapi.unicourt.com/normJudge/NATY2LJwigb5HFRir/associatedNormAttorneys?pageNumber=1", required = true, value = "")

  public URI getAssociatedNormAttorneysAPI() {
    return associatedNormAttorneysAPI;
  }


  public void setAssociatedNormAttorneysAPI(URI associatedNormAttorneysAPI) {
    
    
    
    this.associatedNormAttorneysAPI = associatedNormAttorneysAPI;
  }


  public PossibleNormJudge associatedNormLawFirmsAPI(URI associatedNormLawFirmsAPI) {
    
    
    
    
    this.associatedNormLawFirmsAPI = associatedNormLawFirmsAPI;
    return this;
  }

   /**
   * Get associatedNormLawFirmsAPI
   * @return associatedNormLawFirmsAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "https://enterpriseapi.unicourt.com/normJudge/NATY2LJwigb5HFRir/associatedNormLawFirms?pageNumber=1", required = true, value = "")

  public URI getAssociatedNormLawFirmsAPI() {
    return associatedNormLawFirmsAPI;
  }


  public void setAssociatedNormLawFirmsAPI(URI associatedNormLawFirmsAPI) {
    
    
    
    this.associatedNormLawFirmsAPI = associatedNormLawFirmsAPI;
  }


  public PossibleNormJudge associatedNormPartiesAPI(URI associatedNormPartiesAPI) {
    
    
    
    
    this.associatedNormPartiesAPI = associatedNormPartiesAPI;
    return this;
  }

   /**
   * Get associatedNormPartiesAPI
   * @return associatedNormPartiesAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "https://enterpriseapi.unicourt.com/normJudge/NATY2LJwigb5HFRir/associatedNormParties?pageNumber=1", required = true, value = "")

  public URI getAssociatedNormPartiesAPI() {
    return associatedNormPartiesAPI;
  }


  public void setAssociatedNormPartiesAPI(URI associatedNormPartiesAPI) {
    
    
    
    this.associatedNormPartiesAPI = associatedNormPartiesAPI;
  }


  public PossibleNormJudge bestMatch(Boolean bestMatch) {
    
    
    
    
    this.bestMatch = bestMatch;
    return this;
  }

   /**
   * Get bestMatch
   * @return bestMatch
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "false", required = true, value = "")

  public Boolean getBestMatch() {
    return bestMatch;
  }


  public void setBestMatch(Boolean bestMatch) {
    
    
    
    this.bestMatch = bestMatch;
  }


  public PossibleNormJudge caseCountAnalyticsByNormJudgeAPI(URI caseCountAnalyticsByNormJudgeAPI) {
    
    
    
    
    this.caseCountAnalyticsByNormJudgeAPI = caseCountAnalyticsByNormJudgeAPI;
    return this;
  }

   /**
   * Get caseCountAnalyticsByNormJudgeAPI
   * @return caseCountAnalyticsByNormJudgeAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getCaseCountAnalyticsByNormJudgeAPI() {
    return caseCountAnalyticsByNormJudgeAPI;
  }


  public void setCaseCountAnalyticsByNormJudgeAPI(URI caseCountAnalyticsByNormJudgeAPI) {
    
    
    
    this.caseCountAnalyticsByNormJudgeAPI = caseCountAnalyticsByNormJudgeAPI;
  }


  public PossibleNormJudge confidenceScore(Float confidenceScore) {
    
    
    
    
    this.confidenceScore = confidenceScore;
    return this;
  }

   /**
   * Get confidenceScore
   * @return confidenceScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Float getConfidenceScore() {
    return confidenceScore;
  }


  public void setConfidenceScore(Float confidenceScore) {
    
    
    
    this.confidenceScore = confidenceScore;
  }


  public PossibleNormJudge normJudgeAPI(URI normJudgeAPI) {
    
    
    
    
    this.normJudgeAPI = normJudgeAPI;
    return this;
  }

   /**
   * Link to Details For the Judge.
   * @return normJudgeAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "https://enterpriseapi.unicourt.com/normJudge/NJUD3Ygn4ooAvNxAmd", required = true, value = "Link to Details For the Judge.")

  public URI getNormJudgeAPI() {
    return normJudgeAPI;
  }


  public void setNormJudgeAPI(URI normJudgeAPI) {
    
    
    
    this.normJudgeAPI = normJudgeAPI;
  }


  public PossibleNormJudge normJudgeId(String normJudgeId) {
    
    
    if (normJudgeId != null && normJudgeId.length() < 18) {
      throw new IllegalArgumentException("Invalid value for normJudgeId. Length must be greater than or equal to 18.");
    }
    
    this.normJudgeId = normJudgeId;
    return this;
  }

   /**
   * Get normJudgeId
   * @return normJudgeId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNormJudgeId() {
    return normJudgeId;
  }


  public void setNormJudgeId(String normJudgeId) {
    
    
    if (normJudgeId != null && normJudgeId.length() < 18) {
      throw new IllegalArgumentException("Invalid value for normJudgeId. Length must be greater than or equal to 18.");
    }
    this.normJudgeId = normJudgeId;
  }


  public PossibleNormJudge normJudgeName(String normJudgeName) {
    
    
    
    
    this.normJudgeName = normJudgeName;
    return this;
  }

   /**
   * Get normJudgeName
   * @return normJudgeName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNormJudgeName() {
    return normJudgeName;
  }


  public void setNormJudgeName(String normJudgeName) {
    
    
    
    this.normJudgeName = normJudgeName;
  }


  public PossibleNormJudge _object(String _object) {
    
    
    if (_object != null && _object.length() < 17) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 17.");
    }
    
    this._object = _object;
    return this;
  }

   /**
   * Name of the object
   * @return _object
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "PossibleNormJudge", required = true, value = "Name of the object")

  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    
    
    if (_object != null && _object.length() < 17) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 17.");
    }
    this._object = _object;
  }


  public PossibleNormJudge scoreConstituents(PossibleNormJudgeScoreConstituents scoreConstituents) {
    
    
    
    
    this.scoreConstituents = scoreConstituents;
    return this;
  }

   /**
   * Get scoreConstituents
   * @return scoreConstituents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public PossibleNormJudgeScoreConstituents getScoreConstituents() {
    return scoreConstituents;
  }


  public void setScoreConstituents(PossibleNormJudgeScoreConstituents scoreConstituents) {
    
    
    
    this.scoreConstituents = scoreConstituents;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PossibleNormJudge instance itself
   */
  public PossibleNormJudge putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PossibleNormJudge possibleNormJudge = (PossibleNormJudge) o;
    return Objects.equals(this.associatedNormAttorneysAPI, possibleNormJudge.associatedNormAttorneysAPI) &&
        Objects.equals(this.associatedNormLawFirmsAPI, possibleNormJudge.associatedNormLawFirmsAPI) &&
        Objects.equals(this.associatedNormPartiesAPI, possibleNormJudge.associatedNormPartiesAPI) &&
        Objects.equals(this.bestMatch, possibleNormJudge.bestMatch) &&
        Objects.equals(this.caseCountAnalyticsByNormJudgeAPI, possibleNormJudge.caseCountAnalyticsByNormJudgeAPI) &&
        Objects.equals(this.confidenceScore, possibleNormJudge.confidenceScore) &&
        Objects.equals(this.normJudgeAPI, possibleNormJudge.normJudgeAPI) &&
        Objects.equals(this.normJudgeId, possibleNormJudge.normJudgeId) &&
        Objects.equals(this.normJudgeName, possibleNormJudge.normJudgeName) &&
        Objects.equals(this._object, possibleNormJudge._object) &&
        Objects.equals(this.scoreConstituents, possibleNormJudge.scoreConstituents)&&
        Objects.equals(this.additionalProperties, possibleNormJudge.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associatedNormAttorneysAPI, associatedNormLawFirmsAPI, associatedNormPartiesAPI, bestMatch, caseCountAnalyticsByNormJudgeAPI, confidenceScore, normJudgeAPI, normJudgeId, normJudgeName, _object, scoreConstituents, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PossibleNormJudge {\n");
    sb.append("    associatedNormAttorneysAPI: ").append(toIndentedString(associatedNormAttorneysAPI)).append("\n");
    sb.append("    associatedNormLawFirmsAPI: ").append(toIndentedString(associatedNormLawFirmsAPI)).append("\n");
    sb.append("    associatedNormPartiesAPI: ").append(toIndentedString(associatedNormPartiesAPI)).append("\n");
    sb.append("    bestMatch: ").append(toIndentedString(bestMatch)).append("\n");
    sb.append("    caseCountAnalyticsByNormJudgeAPI: ").append(toIndentedString(caseCountAnalyticsByNormJudgeAPI)).append("\n");
    sb.append("    confidenceScore: ").append(toIndentedString(confidenceScore)).append("\n");
    sb.append("    normJudgeAPI: ").append(toIndentedString(normJudgeAPI)).append("\n");
    sb.append("    normJudgeId: ").append(toIndentedString(normJudgeId)).append("\n");
    sb.append("    normJudgeName: ").append(toIndentedString(normJudgeName)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    scoreConstituents: ").append(toIndentedString(scoreConstituents)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("associatedNormAttorneysAPI");
    openapiFields.add("associatedNormLawFirmsAPI");
    openapiFields.add("associatedNormPartiesAPI");
    openapiFields.add("bestMatch");
    openapiFields.add("caseCountAnalyticsByNormJudgeAPI");
    openapiFields.add("confidenceScore");
    openapiFields.add("normJudgeAPI");
    openapiFields.add("normJudgeId");
    openapiFields.add("normJudgeName");
    openapiFields.add("object");
    openapiFields.add("scoreConstituents");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("associatedNormAttorneysAPI");
    openapiRequiredFields.add("associatedNormLawFirmsAPI");
    openapiRequiredFields.add("associatedNormPartiesAPI");
    openapiRequiredFields.add("bestMatch");
    openapiRequiredFields.add("caseCountAnalyticsByNormJudgeAPI");
    openapiRequiredFields.add("confidenceScore");
    openapiRequiredFields.add("normJudgeAPI");
    openapiRequiredFields.add("normJudgeId");
    openapiRequiredFields.add("normJudgeName");
    openapiRequiredFields.add("object");
    openapiRequiredFields.add("scoreConstituents");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PossibleNormJudge
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PossibleNormJudge.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PossibleNormJudge is not found in the empty JSON string", PossibleNormJudge.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PossibleNormJudge.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("associatedNormAttorneysAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `associatedNormAttorneysAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("associatedNormAttorneysAPI").toString()));
      }
      if (!jsonObj.get("associatedNormLawFirmsAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `associatedNormLawFirmsAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("associatedNormLawFirmsAPI").toString()));
      }
      if (!jsonObj.get("associatedNormPartiesAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `associatedNormPartiesAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("associatedNormPartiesAPI").toString()));
      }
      if (!jsonObj.get("caseCountAnalyticsByNormJudgeAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caseCountAnalyticsByNormJudgeAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseCountAnalyticsByNormJudgeAPI").toString()));
      }
      if (!jsonObj.get("normJudgeAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normJudgeAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normJudgeAPI").toString()));
      }
      if (!jsonObj.get("normJudgeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normJudgeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normJudgeId").toString()));
      }
      if (!jsonObj.get("normJudgeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normJudgeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normJudgeName").toString()));
      }
      if (!jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
      // validate the required field `scoreConstituents`
      PossibleNormJudgeScoreConstituents.validateJsonObject(jsonObj.getAsJsonObject("scoreConstituents"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PossibleNormJudge.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PossibleNormJudge' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PossibleNormJudge> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PossibleNormJudge.class));

       return (TypeAdapter<T>) new TypeAdapter<PossibleNormJudge>() {
           @Override
           public void write(JsonWriter out, PossibleNormJudge value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PossibleNormJudge read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PossibleNormJudge instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PossibleNormJudge given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PossibleNormJudge
  * @throws IOException if the JSON string is invalid with respect to PossibleNormJudge
  */
  public static PossibleNormJudge fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PossibleNormJudge.class);
  }

 /**
  * Convert an instance of PossibleNormJudge to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

