/*
 * UniCourt Enterprise APIs
 * <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BarRecordPreview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SimilarNormAttorney
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SimilarNormAttorney {
  public static final String SERIALIZED_NAME_BAR_RECORD_PREVIEW_ARRAY = "barRecordPreviewArray";
  @SerializedName(SERIALIZED_NAME_BAR_RECORD_PREVIEW_ARRAY)
  private List<BarRecordPreview> barRecordPreviewArray = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NORM_ATTORNEY_A_P_I = "normAttorneyAPI";
  @SerializedName(SERIALIZED_NAME_NORM_ATTORNEY_A_P_I)
  private URI normAttorneyAPI;

  public static final String SERIALIZED_NAME_NORM_ATTORNEY_ID = "normAttorneyId";
  @SerializedName(SERIALIZED_NAME_NORM_ATTORNEY_ID)
  private String normAttorneyId;

  public static final String SERIALIZED_NAME_NORM_ATTORNEY_SIMILARITY_SCORE = "normAttorneySimilarityScore";
  @SerializedName(SERIALIZED_NAME_NORM_ATTORNEY_SIMILARITY_SCORE)
  private Float normAttorneySimilarityScore;

  public static final String SERIALIZED_NAME_OBJECT = "object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private String _object = "SimilarNormAttorney";

  public SimilarNormAttorney() {
  }

  public SimilarNormAttorney barRecordPreviewArray(List<BarRecordPreview> barRecordPreviewArray) {
    
    
    
    
    this.barRecordPreviewArray = barRecordPreviewArray;
    return this;
  }

  public SimilarNormAttorney addBarRecordPreviewArrayItem(BarRecordPreview barRecordPreviewArrayItem) {
    this.barRecordPreviewArray.add(barRecordPreviewArrayItem);
    return this;
  }

   /**
   * Get barRecordPreviewArray
   * @return barRecordPreviewArray
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<BarRecordPreview> getBarRecordPreviewArray() {
    return barRecordPreviewArray;
  }


  public void setBarRecordPreviewArray(List<BarRecordPreview> barRecordPreviewArray) {
    
    
    
    this.barRecordPreviewArray = barRecordPreviewArray;
  }


  public SimilarNormAttorney name(String name) {
    
    
    if (name != null && name.length() < 1) {
      throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 1.");
    }
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    if (name != null && name.length() < 1) {
      throw new IllegalArgumentException("Invalid value for name. Length must be greater than or equal to 1.");
    }
    this.name = name;
  }


  public SimilarNormAttorney normAttorneyAPI(URI normAttorneyAPI) {
    
    
    
    
    this.normAttorneyAPI = normAttorneyAPI;
    return this;
  }

   /**
   * Get normAttorneyAPI
   * @return normAttorneyAPI
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public URI getNormAttorneyAPI() {
    return normAttorneyAPI;
  }


  public void setNormAttorneyAPI(URI normAttorneyAPI) {
    
    
    
    this.normAttorneyAPI = normAttorneyAPI;
  }


  public SimilarNormAttorney normAttorneyId(String normAttorneyId) {
    
    
    if (normAttorneyId != null && normAttorneyId.length() < 18) {
      throw new IllegalArgumentException("Invalid value for normAttorneyId. Length must be greater than or equal to 18.");
    }
    
    this.normAttorneyId = normAttorneyId;
    return this;
  }

   /**
   * Get normAttorneyId
   * @return normAttorneyId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNormAttorneyId() {
    return normAttorneyId;
  }


  public void setNormAttorneyId(String normAttorneyId) {
    
    
    if (normAttorneyId != null && normAttorneyId.length() < 18) {
      throw new IllegalArgumentException("Invalid value for normAttorneyId. Length must be greater than or equal to 18.");
    }
    this.normAttorneyId = normAttorneyId;
  }


  public SimilarNormAttorney normAttorneySimilarityScore(Float normAttorneySimilarityScore) {
    
    
    
    
    this.normAttorneySimilarityScore = normAttorneySimilarityScore;
    return this;
  }

   /**
   * Get normAttorneySimilarityScore
   * @return normAttorneySimilarityScore
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Float getNormAttorneySimilarityScore() {
    return normAttorneySimilarityScore;
  }


  public void setNormAttorneySimilarityScore(Float normAttorneySimilarityScore) {
    
    
    
    this.normAttorneySimilarityScore = normAttorneySimilarityScore;
  }


  public SimilarNormAttorney _object(String _object) {
    
    
    if (_object != null && _object.length() < 19) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 19.");
    }
    
    this._object = _object;
    return this;
  }

   /**
   * Get _object
   * @return _object
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "SimilarNormAttorney", required = true, value = "")

  public String getObject() {
    return _object;
  }


  public void setObject(String _object) {
    
    
    if (_object != null && _object.length() < 19) {
      throw new IllegalArgumentException("Invalid value for _object. Length must be greater than or equal to 19.");
    }
    this._object = _object;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SimilarNormAttorney instance itself
   */
  public SimilarNormAttorney putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimilarNormAttorney similarNormAttorney = (SimilarNormAttorney) o;
    return Objects.equals(this.barRecordPreviewArray, similarNormAttorney.barRecordPreviewArray) &&
        Objects.equals(this.name, similarNormAttorney.name) &&
        Objects.equals(this.normAttorneyAPI, similarNormAttorney.normAttorneyAPI) &&
        Objects.equals(this.normAttorneyId, similarNormAttorney.normAttorneyId) &&
        Objects.equals(this.normAttorneySimilarityScore, similarNormAttorney.normAttorneySimilarityScore) &&
        Objects.equals(this._object, similarNormAttorney._object)&&
        Objects.equals(this.additionalProperties, similarNormAttorney.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barRecordPreviewArray, name, normAttorneyAPI, normAttorneyId, normAttorneySimilarityScore, _object, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimilarNormAttorney {\n");
    sb.append("    barRecordPreviewArray: ").append(toIndentedString(barRecordPreviewArray)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    normAttorneyAPI: ").append(toIndentedString(normAttorneyAPI)).append("\n");
    sb.append("    normAttorneyId: ").append(toIndentedString(normAttorneyId)).append("\n");
    sb.append("    normAttorneySimilarityScore: ").append(toIndentedString(normAttorneySimilarityScore)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("barRecordPreviewArray");
    openapiFields.add("name");
    openapiFields.add("normAttorneyAPI");
    openapiFields.add("normAttorneyId");
    openapiFields.add("normAttorneySimilarityScore");
    openapiFields.add("object");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("barRecordPreviewArray");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("normAttorneyAPI");
    openapiRequiredFields.add("normAttorneyId");
    openapiRequiredFields.add("normAttorneySimilarityScore");
    openapiRequiredFields.add("object");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SimilarNormAttorney
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SimilarNormAttorney.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SimilarNormAttorney is not found in the empty JSON string", SimilarNormAttorney.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SimilarNormAttorney.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("barRecordPreviewArray").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `barRecordPreviewArray` to be an array in the JSON string but got `%s`", jsonObj.get("barRecordPreviewArray").toString()));
      }

      JsonArray jsonArraybarRecordPreviewArray = jsonObj.getAsJsonArray("barRecordPreviewArray");
      // validate the required field `barRecordPreviewArray` (array)
      for (int i = 0; i < jsonArraybarRecordPreviewArray.size(); i++) {
        BarRecordPreview.validateJsonObject(jsonArraybarRecordPreviewArray.get(i).getAsJsonObject());
      };
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("normAttorneyAPI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normAttorneyAPI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normAttorneyAPI").toString()));
      }
      if (!jsonObj.get("normAttorneyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `normAttorneyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normAttorneyId").toString()));
      }
      if (!jsonObj.get("object").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `object` to be a primitive type in the JSON string but got `%s`", jsonObj.get("object").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SimilarNormAttorney.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SimilarNormAttorney' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SimilarNormAttorney> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SimilarNormAttorney.class));

       return (TypeAdapter<T>) new TypeAdapter<SimilarNormAttorney>() {
           @Override
           public void write(JsonWriter out, SimilarNormAttorney value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SimilarNormAttorney read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SimilarNormAttorney instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SimilarNormAttorney given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SimilarNormAttorney
  * @throws IOException if the JSON string is invalid with respect to SimilarNormAttorney
  */
  public static SimilarNormAttorney fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SimilarNormAttorney.class);
  }

 /**
  * Convert an instance of SimilarNormAttorney to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

